---
- type: replace
  path: /releases/name=bosh-libvirt-cpi
  value:
    name: bosh-libvirt-cpi
    url: file:///tmp/bosh-libvirt-cpi.tgz # bosh create-release --force --tarball /tmp/bosh-libvirt-cpi.tgz
